name: Documentation

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  URHO3D_DOCS: ON
  URHO3D_ENABLE_ALL: ON
  URHO3D_CSHARP: ON
  BUILD_SHARED_LIBS: ON

jobs:
  Documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: rbfx
          repository: rbfx/rbfx
          ref: master

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install -y --no-install-recommends doxygen

      - name: Generate
        shell: bash
        run: |
          # Source code must be outside of docs repo so by including root docs dir we dont also consume ThirdParty source code
          mv rbfx ..
          cd ..
          mkdir cmake-build-rbfx
          cd cmake-build-rbfx
          cmake ../rbfx

          cd ..
          mkdir cmake-build-docs
          cd cmake-build-docs
          cmake ../rbfx-docs

      - name: Build
        shell: bash
        run: |
          cd ../cmake-build-docs
          cmake --build . --target doc
          mv html ../rbfx-docs/html    # Allow deployment/artifact steps can find this dir

      - name: Deploy
        if: github.repository == 'rbfx/rbfx-docs'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.RBFX_DOCS_DEPLOY_TOKEN }}
          external_repository: rbfx/rbfx.github.io
          cname: rebelfork.io
          publish_dir: html
          publish_branch: master
          force_orphan: true

      - uses: actions/upload-artifact@v2
        with:
          name: 'rbfx-docs-${{ github.sha }}'
          path: html
